"""Citas incluyen id medico con nombres explícitos

Revision ID: 0961d21a4136
Revises: 
Create Date: 2025-03-04 15:45:27.930781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0961d21a4136'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medico_id', sa.Integer(), nullable=False))
        batch_op.alter_column('paciente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_cita_medico_id', 'medico', ['medico_id'], ['id'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cita_medico_id', type_='foreignkey')
        batch_op.alter_column('paciente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('medico_id')

    # ### end Alembic commands ###
